name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Bratislava

          template: repository
          user: marek-guran
          repo: Rozvrh-App
          
          
          plugin_languages: yes
